#! /bin/sh

## env vars ##
export WALLPAPER="$HOME/wallpaper/wallpaperr.jpg"

pgrep -x sxhkd > /dev/null || sxhkd &

rule() { bspc rule -a "$@" & }

xsetroot -cursor_name left_ptr &

bspc monitor DP-4 -d I II III 
bspc monitor HDMI-0 -d IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

feh --bg-fill $WALLPAPER

rule discord desktop=^4

$HOME/.dotfiles/polybar/launch.sh
